#! /bin/sh
# /etc/init.d/ws2812XmlServer
#

touch /var/lock/ws2812XmlServer

case "$1" in
  start)
    echo "Starting script ws2812XmlServer"
    /opt/ws2812XmlServer/ws2812XmlServerd.pl
    ;;
  stop)
    echo "Stopping script ws2812XmlServer"
    kill -9 $(pidof perl)
    rm -f /opt/ws2812XmlServer/ws2812XmlServer.err
    rm -f /opt/ws2812XmlServer/ws2812XmlServer.log
    rm -f /opt/ws2812XmlServer/ws2812XmlServer.out
    rm -f /opt/ws2812XmlServer/ws2812XmlServer.pid
    ;;
  *)
    echo "Usage: /etc/init.d/ws2812XmlServer {start|stop}"
    exit 1
    ;;
esac

exit 0
